name: Running Cypress Xporter

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file from GitHub Secrets
        run: |
          echo "Generating .env file..."
          echo "${{ secrets.APP_SECRET }}" >> .env

      # Cypress Test
      - name: Cypress Test
        run: |
          echo "Running Cypress tests..."
          npm install
          npx cypress run

      # ✅ Always run this step, even if Cypress tests fail
      - name: Cypress Xporter
        if: always()
        run: |
          echo "Publish Mochawesome Report with Cypress Xporter..."
          npx cypress-xporter --jira --testrail --confluence
